server:
  port: ${SERVER_PORT:8085}
  servlet:
    context-path: ${CONTEXT_PATH:/api/v1}
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
application:
  security:
    username: admin
    password: Admin@123